language: php

php:
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

matrix:
  fast_finish: true

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: vendor/bin/phpunit

notifications:
  email:
    - prager.adam87@gmail.com
